name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        configuration: [Debug, Release]

    steps:
      - uses: actions/checkout@v2

      - name: Setup NuGet.exe
        uses: nuget/setup-nuget@v1

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Build Project
        run: |
          nuget.exe restore
          MSBuild.exe EndlessLauncher.sln /p:Configuration=${{ matrix.configuration }}

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.configuration }}
          path: "*/bin/${{ matrix.configuration }}/*.exe"

