name: CI

on:
  push:
    branches:
      - master
    tags:
        - "v*"
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        configuration: [Debug, Release]

    steps:
      - uses: actions/checkout@v2

      - name: Setup NuGet.exe
        uses: nuget/setup-nuget@v1

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Build Project
        run: |
          nuget restore EndlessLauncher.sln
          MSBuild.exe EndlessLauncher.sln /p:Configuration=${{ matrix.configuration }}

      - name: Build Endless Key Project
        run: |
          MSBuild.exe EndlessKeyLauncher.sln /p:Configuration=${{ matrix.configuration }}

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            KolibriShortcut/bin/Release/Endless Key Launcher.exe
            EndlessLauncher/bin/Release/Endless Launcher.exe

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.configuration }}
          path: "*/bin/${{ matrix.configuration }}/*.exe"

